name = "sub-converter"
main = "worker.js"
compatibility_date = "2024-03-01"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  { binding = "CONFIGS", id = "2949a978eece4792ac0085e24be897cf" }
]
